version: '3.3'
services:
  postgres:
    image: "postgres:9.6-alpine"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
  elasticsearch:
    image: "elasticsearch:2.4-alpine"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  backend:
    image: "factycznie/factycznie-backend:latest"
    environment:
      - "POSTGRES_PORT_5432_TCP_PORT=5432"
      - "POSTGRES_PORT_5432_TCP_ADDR=postgres"
      - "BONSAI_URL=http://elasticsearch:9200/"
      - "ELASTIC_USERNAME=elastic"
      - "ELASTIC_PASSWORD=changeme"
      - "DJANGO_SETTINGS_MODULE=factcoin.settings.production"
  frontend:
    image: "factycznie/factycznie-frontend:latest"
    ports:
      - "80:80"
      - "443:443"
volumes:
  redis-data:
  postgres-data:
  elasticsearch-data:
