version: '3.3'
services:
  postgres:
    image: "postgres:9.6-alpine"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
  elasticsearch:
    image: "elasticsearch:2.4-alpine"
#    ports:
#      - "9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  nginx:
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx/mime.types:/etc/nginx/mime.types
  backend:
    image: "factycznie/factycznie_backend:latest"
    networks:
      - factycznie-network
#    ports:
#      - "8000"
    environment:
      - "POSTGRES_PORT_5432_TCP_PORT=5432"
      - "POSTGRES_PORT_5432_TCP_ADDR=postgres"
      - "BONSAI_URL=http://elasticsearch:9200/"
      - "ELASTIC_USERNAME=elastic"
      - "ELASTIC_PASSWORD=changeme"
      - "DJANGO_SETTINGS_MODULE=factcoin.settings.production"
  frontend:
    image: "factycznie/factycznie_frontend:latest"
    networks:
      - factycznie-network
#    ports:
#      - "5000"
volumes:
  redis-data:
  postgres-data:
  elasticsearch-data:
configs:
  nginx-config:
    file: ./nginx/nginx.conf
