version: '3'
services:
  postgres:
    image: "postgres:9.6-alpine"
    networks:
      - factcoin-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    networks:
      - factcoin-net
    volumes:
      - redis-data:/data
  elasticsearch:
    image: "elasticsearch:2.4-alpine"
    ports:
      - "9200"
    networks:
      - factcoin-net
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  factcoin:
    image: "factcoin/factcoin:latest"
    ports:
      - "80:8000"
    environment:
      - "POSTGRES_PORT_5432_TCP_PORT=5432"
      - "POSTGRES_PORT_5432_TCP_ADDR=postgres"
      - "BONSAI_URL=http://elasticsearch:9200/"
      - "ELASTIC_USERNAME=elastic"
      - "ELASTIC_PASSWORD=changeme"
      - "DJANGO_SETTINGS_MODULE=factcoin.settings.production"
    networks:
      - factcoin-net
volumes:
  redis-data:
  postgres-data:
  elasticsearch-data:
networks:
  factcoin-net:
