apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.11.0 (39ad614)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: backend
    spec:
      containers:
      - env:
        - name: BONSAI_URL
          value: http://elasticsearch:9200/
        - name: DJANGO_SETTINGS_MODULE
          value: factcoin.settings.production
        - name: ELASTIC_PASSWORD
          value: changeme
        - name: ELASTIC_USERNAME
          value: elastic
        - name: POSTGRES_PORT_5432_TCP_ADDR
          value: postgres
        - name: POSTGRES_PORT_5432_TCP_PORT
          value: "5432"
        image: factycznie/factycznie-backend:latest
        name: backend
        resources: {}
      restartPolicy: Always
status: {}
